name: SocialNetwork Pull Request Validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'src/webapp.client**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'src/webapp.client**'      

jobs:  
  test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v3
      - name: Build 
        run: dotnet build SocialNetwork.slnf
      - name: Test
        run: dotnet test SocialNetwork.slnf